[versions]
lifecycleLivedataKtx = "2.6.2"
lifecycleViewmodelKtx = "2.6.2"
roomCompiler = "2.5.2"
roomRuntime = "2.5.2"
appcompat = "1.7.0"
material = "1.12.0"
org-jetbrains-kotlin-android = "1.9.0"
constraintlayout = "2.1.4"

[libraries]
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycleViewmodelKtx" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "roomRuntime" }
lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycleLivedataKtx" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "roomCompiler" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }

[plugins]
org-jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "org-jetbrains-kotlin-android" }